Updating flexible mink with dependencies (3.1.0)
Medology/behat-google-place-autocomplete pull request #101
Opened 2021-12-17 21:24 UTC by oliveiraweb

Updating dependency on composer.json so I will be able to update the Flexible Mint on STDCheck.

2021-12-17 22:17 UTC, VitorTS approved these changes

2021-12-17 22:18 UTC, VitorTS approved these changes

2021-12-20 13:27 UTC, PayneWheat reviewed
What happened with scrutinizer?

2021-12-20 14:20 UTC, johnnie502 approved these changes

2021-12-20 14:29 UTC, johnnie502 approved these changes

2021-12-20 16:07 UTC, Chekote requested changes

2021-12-20 16:07 UTC, Chekote commented on composer.json
> +    "medology/flexible-mink": "~3.1.0",
Why are there no changes to the Composer lock file? Updating the JSON file without actually running `composer update medology/flexible-mink` is not going to cause the new version to be used. Updating the JSON file only states that you require it.

2021-12-20 18:16 UTC, Chekote approved these changes

2021-12-20 21:12 UTC, merged